version: '2.2'
volumes:
  lgsm:
services:
  lgsm:
    init: true
    user: root
    image: gameservermanagers/linuxgsm-docker
    command:
      - /bin/bash
      - -exc
      - |
        apt-get update
        #apt-get install -y lib32z1 expect telnet sudo
        apt-get install -y sudo
        echo 'linuxgsm  ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/lgsm
        echo 'export ENABLE_RUST_EAC="${ENABLE_RUST_EAC:-}"' > /tmp/rust-docker-environment.sh
        chown linuxgsm: /home/linuxgsm /home/linuxgsm/serverfiles /home/linuxgsm/serverfiles/oxide
        chown -R linuxgsm: /home/linuxgsm/serverfiles/oxide/config
        su - linuxgsm -c /custom-rust-server.sh
    volumes:
      - lgsm:/home/linuxgsm
      - ./utils/custom-rust-server.sh:/custom-rust-server.sh:ro
      - ./plugin-configs/:/home/linuxgsm/serverfiles/oxide/config/:rw

    ports:
      - ${RUST_RCON_INTERFACE:-127.0.0.1}:28016:28016
      - 0.0.0.0:28015:28015/udp
