version: '2.2'
volumes:
  lgsm:
services:
  lgsm:
    init: true
    user: root
    image: gameservermanagers/linuxgsm-docker
    command:
      - /bin/bash
      - -exc
      - |
        apt-get update
        #apt-get install -y lib32z1 expect telnet sudo
        apt-get install -y sudo
        echo 'linuxgsm  ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/lgsm
        echo 'export ENABLE_RUST_EAC="${ENABLE_RUST_EAC:-}"' > /tmp/rust-docker-environment.sh
        lgsm_uid="$$(id -u linuxgsm)"
        lgsm_gid="$$(id -g linuxgsm)"
        if [ ! "$$lgsm_uid" = 1000 ]; then
          sed -i "s/:$$lgsm_uid:$$lgsm_gid:/:1000:1000:/" /etc/passwd
          sed -i "s/:$$lgsm_gid:/:1000:/" /etc/group
        fi
        if [ ! "$$(stat -c '%U' /home/linuxgsm)" = linuxgsm ]; then
          chown -R linuxgsm: /home/linuxgsm
        fi
        chown linuxgsm: /home/linuxgsm /home/linuxgsm/serverfiles /home/linuxgsm/serverfiles/oxide
        chown -R linuxgsm: /home/linuxgsm/serverfiles/oxide/config
        su - linuxgsm -c /custom-rust-server.sh
    volumes:
      - lgsm:/home/linuxgsm
      - ./utils/custom-rust-server.sh:/custom-rust-server.sh:ro
      - ./plugin-configs/:/home/linuxgsm/serverfiles/oxide/config/:rw
      - ./utils/get-or-update-plugins.sh:/get-or-update-plugins.sh:ro
      - ./plugins.txt:/plugins.txt:rw
    ports:
      - ${RUST_RCON_INTERFACE:-127.0.0.1}:28016:28016
      - 0.0.0.0:28015:28015/udp
